export const ACTION = Object.freeze({
  MOVE_LEFT: "MOVE_LEFT", MOVE_RIGHT: "MOVE_RIGHT", MOVE_UP: "MOVE_UP", MOVE_DOWN: "MOVE_DOWN",
  CHECK: "CHECK", READ_CURRENT: "READ_CURRENT", READ_OVERVIEW: "READ_OVERVIEW",
  HINT: "HINT", RESTART: "RESTART", EXIT: "EXIT"
});
